---
title: "Writing Functions"
author: "AJ Catalano"
date: "1/3/2022"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

## Simple Z-Score function

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

# computing z-scores
(x_vec - mean(x_vec)) / sd(x_vec)
```

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x_vec)
```

Using z_scores with other things. These should give errors.

```{r, error = TRUE}
z_scores(3)
z_scores("my_name_is_aj")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

Revising z_scores

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must have at least numbers")
  }
    
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x_vec)
```

## Functions with multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must have at least numbers")
  }
    
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

Checking to see if function works

```{r}
x_vec = rnorm(1000)
mean_and_sd(x_vec)
```

## Multiple inputs

```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4, sd = 3)
  )

sim_data |> 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

Turning this into a function

```{r}
# can include default values by specifying them in function statement

sim_mean_sd = function(samp_size, mu, sigma) {
  
  sim_data = 
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

  sim_data |> 
    summarize(
      mean = mean(x),
      sd = sd(x)
  )

}

# testing function
sim_mean_sd(100, 6, 3)
```

## Scraping Amazon

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

# what about the next page of reviews?
```

Turning this into a function

```{r}
# note that only change across pages is the url

read_page_reviews = function(url) {
  
  dynamite_html = read_html(url)
  
  review_titles = 
    dynamite_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()

  review_stars = 
    dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()

  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )

  return(reviews)

}

# testing function

dynamite_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

read_page_reviews(dynamite_url)

# reading multiple pages (5) of reviews

dynamite_url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

dynamite_urls = str_c(dynamite_url_base, 1:50)

five_pages_reviews = 
  rbind(
    read_page_reviews(dynamite_urls[1]),
    read_page_reviews(dynamite_urls[2]),
    read_page_reviews(dynamite_urls[3]),
    read_page_reviews(dynamite_urls[4]),
    read_page_reviews(dynamite_urls[5])
)
```

## Mean scoping example

```{r}
f = function(x) {
  
  z = x + y
  
  z
  
}

# x and y are in global env.
x = 1
y = 2

f(x = y)
```

## Functions as arguments

```{r}
my_summary = function(x, summ_func) {
  
  summ_func(x)
  
}

x_vec = rnorm(100, mean = 3, sd = 7)

mean(x_vec)
median(x_vec)

my_summary(x_vec, mean)
my_summary(x_vec, median)
my_summary(x_vec, sd)
my_summary(x_vec, IQR)
```

