---
title: "Iteration and Listcols"
author: "AJ Catalano"
date: "1/3/2022"
output: github_document
---

```{r}
library(tidyverse)
set.seed(1)
```

## Lists

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
  mat = matrix(1:8, nrow = 2, ncol = 4),
  summary = summary(rnorm(100))
)

l$vec_numeric
l[[1]]
mean(l[["vec_numeric"]])
```

## For loops

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
)

list_norm[[1]]
list_norm[[2]]
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must have at least numbers")
  }
    
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

The function can be applied to each list element

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Doing that with a for loop

```{r}
output = vector("list", length = 4)

output[[1]] = mean_and_sd(list_norm[[1]])

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}
```

## `Map`

```{r}
# output identical to for loop
output = map(list_norm, mean_and_sd)
```

Using another function

```{r}
output = map_dbl(list_norm, median)

output = map_df(list_norm, mean_and_sd, .id = "input")
```

## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm
  )

listcol_df |> pull(name)
listcol_df |> pull(samp)

listcol_df |> 
  filter(
    name == "a"
  )
```

Some operations

```{r}
listcol_df$samp

listcol_df$samp[[1]]

mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])

# using map

map(listcol_df$samp, mean_and_sd)

# adding a list column

listcol_df = 
  listcol_df |> 
    mutate(
     summary = map(samp, mean_and_sd),
     medians = map_dbl(samp, median)
    )
listcol_df
```

## Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Getting list columns

```{r}
weather_nest = 
  weather_df |> 
  nest(data = date:tmin)
```

```{r}
weather_nest |> 
  pull(name)

weather_nest |> 
  pull(data)

# looking at nested Waterhole data

weather_nest$data[[3]]
```

Regressing `tmax` on `tmin` for each station

```{r}
lm(tmax ~ tmin, data = weather_nest$data[[1]])
```

Writing a function to regress all three groups

```{r}
weather_lm = function(df) {
  
  lm(tmax ~ tmin, data = df)
  
}

# using for loop

output = vector("list", 3)

for (i in 1:3) {
  
  output[[i]] = lm(tmax ~ tmin, data = weather_nest$data[[i]])
  
}

# using a map

map(weather_nest$data, weather_lm)

# map in a list column

weather_nest |> 
  mutate(
    models = map(data, weather_lm)
  )
```

